name: Deploy Backend & Docker Compose

on:
  push:
    branches:
      - master # ทริกเกอร์เมื่อมีการ Push ไปที่ main branch
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted # บอก GitHub ให้ใช้ Self-Hosted Runner ของคุณ

    steps:
      - name: Checkout Backend Code # Step นี้จะ Checkout โค้ดของ Backend Repository ปัจจุบัน
        uses: actions/checkout@v4

      - name: Pull Backend 
        run: |
          cd /home/BUU/65160309/bluelock/Backend-Bluelock-007/
          git pull origin master

      - name: Build and Deploy Docker Compose # รันคำสั่ง Docker Compose
        run: |
          cd /home/BUU/65160309/bluelock/Backend-Bluelock-007/ 
          docker compose down --volumes         
          docker compose build --no-cache       
          docker compose up -d --force-recreate 